Vagrant.configure(2) do |config|
  config.vm.define :www do |www_config|
    www_config.vm.box = "ubuntu/trusty64"
    www_config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../playbooks/global.yml"
#      ansible.verbose = "vvvv"
    end
  end
end
